spring:
  application:
    name: tm-base
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 1

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
