package com.trackmed.tmmock.domains.enums;

import lombok.Getter;
import lombok.ToString;

@Getter
@ToString
public enum Speciality {
    ALERGISTA("ALERGISTA"),
    ANESTESISTA("ANESTESISTA"),
    ANGIOLOGISTA("ANGIOLOGISTA"),
    CARDIOLOGISTA("CARDIOLOGISTA"),
    CIRURGIAO_PLASTICO("CIRURGIÃO PLÁSTICO"),
    CLINICO_GERAL("CLÍNICO GERAL"),
    DERMATOLOGISTA("DERMATOLOGISTA"),
    ENDOCRINOLOGISTA("ENDOCRINOLOGISTA"),
    GASTROENTEROLOGIA("GASTROENTEROLOGIA"),
    GINECOLOGISTA("GINECOLOGISTA"),
    HOMEOPATA("HOMEOPATA"),
    MASTOLOGISTA("MASTOLOGISTA"),
    NEUROLOGISTA("NEUROLOGISTA"),
    OBSTETRA("OBSTETRA"),
    OCOLOGISTA("OCOLOGISTA"),
    OFTALOLOGISTA("OFTALOLOGISTA"),
    ORTOPEDISTA("ORTOPEDISTA"),
    OTORRINOLARINGOLOGISTA("OTORRINOLARINGOLOGISTA"),
    UROLOGISTA("UROLOGISTA"),
    PEDIATRA("PEDIATRA"),
    PNEUMOLOGISTA("PNEUMOLOGISTA"),
    PSIQUIATRA("PSIQUÍATRA"),
    GERIATRAENTEROLOGIA("GERIATRAENTEROLOGIA"),
    PATOLOGISTA("PATOLOGISTA");

    private String description;

    Speciality(String description) {
        this.description = description;
    }
}
